import { createClient } from "@supabase/supabase-js";

const SUPABASE_URL = process.env.SUPABASE_URL!;
const SUPABASE_SERVICE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY!;

const supabase = createClient(SUPABASE_URL, SUPABASE_SERVICE_KEY);

const cities = [
  { slug: "bali", name: "Bali", country: "Indonesia", country_code: "ID", continent: "Asia", flag_emoji: "🇮🇩", monthly_total_budget_usd: 1200, monthly_rent_usd: 450, monthly_food_usd: 300, monthly_transport_usd: 80, monthly_utilities_usd: 60, internet_speed_mbps: 35, safety_score: 72, english_proficiency: "medium", coworking_count: 45, timezone: "Asia/Makassar", currency_code: "IDR", description: "Bali is the top nomad destination in Asia. Cheap cost of living, warm weather year-round, massive expat community, and dozens of coworking spaces in Canggu and Seminyak.", best_for: ["Developers", "Designers", "Content creators"] },
  { slug: "lisbon", name: "Lisbon", country: "Portugal", country_code: "PT", continent: "Europe", flag_emoji: "🇵🇹", monthly_total_budget_usd: 2200, monthly_rent_usd: 1100, monthly_food_usd: 500, monthly_transport_usd: 100, monthly_utilities_usd: 150, internet_speed_mbps: 85, safety_score: 88, english_proficiency: "high", coworking_count: 60, timezone: "Europe/Lisbon", currency_code: "EUR", description: "Lisbon is Europe's most affordable capital and a top choice for Indian techies. Portugal has a dedicated Digital Nomad Visa (D8). Great food, walkable city, and a thriving startup scene.", best_for: ["Developers", "PMs", "Designers"] },
  { slug: "tbilisi", name: "Tbilisi", country: "Georgia", country_code: "GE", continent: "Europe", flag_emoji: "🇬🇪", monthly_total_budget_usd: 900, monthly_rent_usd: 350, monthly_food_usd: 250, monthly_transport_usd: 50, monthly_utilities_usd: 60, internet_speed_mbps: 50, safety_score: 80, english_proficiency: "medium", coworking_count: 20, timezone: "Asia/Tbilisi", currency_code: "GEL", description: "Georgia is a hidden gem. Indians can stay visa-free for 1 full year. Cost of living is extremely low, food is amazing, and the country has a 1% flat income tax if you register as a business.", best_for: ["Developers", "Freelancers", "Data analysts"] },
  { slug: "chiang-mai", name: "Chiang Mai", country: "Thailand", country_code: "TH", continent: "Asia", flag_emoji: "🇹🇭", monthly_total_budget_usd: 1000, monthly_rent_usd: 380, monthly_food_usd: 280, monthly_transport_usd: 80, monthly_utilities_usd: 60, internet_speed_mbps: 40, safety_score: 78, english_proficiency: "medium", coworking_count: 30, timezone: "Asia/Bangkok", currency_code: "THB", description: "Chiang Mai is Asia's original digital nomad city. Low cost, great food, beautiful temples, and a massive nomad community. Thailand offers 30-day visa-free entry for Indian passport holders.", best_for: ["Developers", "Writers", "Designers"] },
  { slug: "medellin", name: "Medellín", country: "Colombia", country_code: "CO", continent: "Americas", flag_emoji: "🇨🇴", monthly_total_budget_usd: 1100, monthly_rent_usd: 420, monthly_food_usd: 300, monthly_transport_usd: 80, monthly_utilities_usd: 60, internet_speed_mbps: 55, safety_score: 65, english_proficiency: "low", coworking_count: 35, timezone: "America/Bogota", currency_code: "COP", description: "Medellín transformed from the world's most dangerous city to one of the most innovative. Eternal spring climate, low cost, and a growing tech scene.", best_for: ["Developers", "Entrepreneurs", "Data engineers"] },
  { slug: "budapest", name: "Budapest", country: "Hungary", country_code: "HU", continent: "Europe", flag_emoji: "🇭🇺", monthly_total_budget_usd: 1600, monthly_rent_usd: 700, monthly_food_usd: 450, monthly_transport_usd: 100, monthly_utilities_usd: 120, internet_speed_mbps: 90, safety_score: 82, english_proficiency: "high", coworking_count: 40, timezone: "Europe/Budapest", currency_code: "HUF", description: "Budapest is one of Europe's most beautiful and affordable capitals. Fast internet, great food, and a thriving tech community. Part of Schengen — requires Schengen visa for Indians.", best_for: ["Developers", "PMs", "Data analysts"] },
  { slug: "prague", name: "Prague", country: "Czech Republic", country_code: "CZ", continent: "Europe", flag_emoji: "🇨🇿", monthly_total_budget_usd: 1800, monthly_rent_usd: 850, monthly_food_usd: 500, monthly_transport_usd: 120, monthly_utilities_usd: 150, internet_speed_mbps: 95, safety_score: 85, english_proficiency: "high", coworking_count: 50, timezone: "Europe/Prague", currency_code: "CZK", description: "Prague is a stunning medieval city with a world-class tech scene. High-speed internet, safe streets, and great café culture. Schengen area — requires visa for Indians.", best_for: ["Developers", "Designers", "PMs"] },
  { slug: "tallinn", name: "Tallinn", country: "Estonia", country_code: "EE", continent: "Europe", flag_emoji: "🇪🇪", monthly_total_budget_usd: 1900, monthly_rent_usd: 850, monthly_food_usd: 500, monthly_transport_usd: 100, monthly_utilities_usd: 150, internet_speed_mbps: 100, safety_score: 86, english_proficiency: "high", coworking_count: 30, timezone: "Europe/Tallinn", currency_code: "EUR", description: "Estonia is the most digitally advanced country in the world. Built Skype, TransferWise. Has the world's first Digital Nomad Visa. Schengen area — requires Schengen visa for Indians.", best_for: ["Developers", "Founders", "Fintech engineers"] },
  { slug: "mexico-city", name: "Mexico City", country: "Mexico", country_code: "MX", continent: "Americas", flag_emoji: "🇲🇽", monthly_total_budget_usd: 1300, monthly_rent_usd: 550, monthly_food_usd: 350, monthly_transport_usd: 80, monthly_utilities_usd: 80, internet_speed_mbps: 60, safety_score: 60, english_proficiency: "medium", coworking_count: 55, timezone: "America/Mexico_City", currency_code: "MXN", description: "CDMX is the biggest nomad boom city of 2024. Indians can enter visa-free for 180 days. Great food, vibrant culture, strong tech and startup scene in Roma/Condesa neighborhoods.", best_for: ["Developers", "Designers", "Marketers"] },
  { slug: "bangkok", name: "Bangkok", country: "Thailand", country_code: "TH", continent: "Asia", flag_emoji: "🇹🇭", monthly_total_budget_usd: 1100, monthly_rent_usd: 450, monthly_food_usd: 300, monthly_transport_usd: 100, monthly_utilities_usd: 80, internet_speed_mbps: 45, safety_score: 75, english_proficiency: "medium", coworking_count: 50, timezone: "Asia/Bangkok", currency_code: "THB", description: "Bangkok is Southeast Asia's megacity — modern, connected, and surprisingly affordable. Great street food, excellent hospitals, and easy access to the rest of Asia.", best_for: ["Developers", "PMs", "Data engineers"] },
  { slug: "barcelona", name: "Barcelona", country: "Spain", country_code: "ES", continent: "Europe", flag_emoji: "🇪🇸", monthly_total_budget_usd: 2500, monthly_rent_usd: 1300, monthly_food_usd: 600, monthly_transport_usd: 120, monthly_utilities_usd: 150, internet_speed_mbps: 92, safety_score: 76, english_proficiency: "medium", coworking_count: 70, timezone: "Europe/Madrid", currency_code: "EUR", description: "Barcelona is one of Europe's most liveable cities. Beach, mountains, amazing food, and a thriving tech scene. Spain has a Digital Nomad Visa since 2023.", best_for: ["Developers", "Designers", "Founders"] },
  { slug: "porto", name: "Porto", country: "Portugal", country_code: "PT", continent: "Europe", flag_emoji: "🇵🇹", monthly_total_budget_usd: 1900, monthly_rent_usd: 900, monthly_food_usd: 450, monthly_transport_usd: 100, monthly_utilities_usd: 120, internet_speed_mbps: 80, safety_score: 90, english_proficiency: "high", coworking_count: 35, timezone: "Europe/Lisbon", currency_code: "EUR", description: "Porto is Portugal's second city and even more affordable than Lisbon. Stunning architecture, world-famous port wine, and a quieter pace of life.", best_for: ["Developers", "Writers", "Designers"] },
  { slug: "taipei", name: "Taipei", country: "Taiwan", country_code: "TW", continent: "Asia", flag_emoji: "🇹🇼", monthly_total_budget_usd: 1600, monthly_rent_usd: 700, monthly_food_usd: 400, monthly_transport_usd: 80, monthly_utilities_usd: 80, internet_speed_mbps: 200, safety_score: 92, english_proficiency: "high", coworking_count: 40, timezone: "Asia/Taipei", currency_code: "TWD", description: "Taipei has the fastest internet in the world, excellent food, and an incredibly safe environment. Taiwan has an e-visa option for Indians.", best_for: ["Developers", "Hardware engineers", "Data scientists"] },
  { slug: "seoul", name: "Seoul", country: "South Korea", country_code: "KR", continent: "Asia", flag_emoji: "🇰🇷", monthly_total_budget_usd: 2000, monthly_rent_usd: 900, monthly_food_usd: 500, monthly_transport_usd: 120, monthly_utilities_usd: 130, internet_speed_mbps: 180, safety_score: 94, english_proficiency: "medium", coworking_count: 60, timezone: "Asia/Seoul", currency_code: "KRW", description: "Seoul is Asia's tech powerhouse. Blazing internet speeds, ultra-modern city, and an exciting culture. South Korea has a Digital Nomad Visa.", best_for: ["Developers", "Product engineers", "Data scientists"] },
  { slug: "cape-town", name: "Cape Town", country: "South Africa", country_code: "ZA", continent: "Africa", flag_emoji: "🇿🇦", monthly_total_budget_usd: 1200, monthly_rent_usd: 500, monthly_food_usd: 300, monthly_transport_usd: 100, monthly_utilities_usd: 80, internet_speed_mbps: 50, safety_score: 55, english_proficiency: "high", coworking_count: 25, timezone: "Africa/Johannesburg", currency_code: "ZAR", description: "Cape Town is one of the world's most beautiful cities. Table Mountain, beaches, wine country. Safety is a concern — stick to known areas.", best_for: ["Developers", "Designers", "Content creators"] },
  { slug: "dubai", name: "Dubai", country: "UAE", country_code: "AE", continent: "Asia", flag_emoji: "🇦🇪", monthly_total_budget_usd: 3500, monthly_rent_usd: 2000, monthly_food_usd: 700, monthly_transport_usd: 300, monthly_utilities_usd: 200, internet_speed_mbps: 120, safety_score: 90, english_proficiency: "high", coworking_count: 80, timezone: "Asia/Dubai", currency_code: "AED", description: "Dubai is the most popular destination for high-earning Indian remote workers. 0% income tax, massive Indian community, and a thriving tech and crypto scene.", best_for: ["Senior developers", "Fintech engineers", "Founders"] },
  { slug: "kuala-lumpur", name: "Kuala Lumpur", country: "Malaysia", country_code: "MY", continent: "Asia", flag_emoji: "🇲🇾", monthly_total_budget_usd: 1000, monthly_rent_usd: 400, monthly_food_usd: 280, monthly_transport_usd: 80, monthly_utilities_usd: 60, internet_speed_mbps: 70, safety_score: 74, english_proficiency: "high", coworking_count: 35, timezone: "Asia/Kuala_Lumpur", currency_code: "MYR", description: "KL is a fantastic base for Indian nomads — English is widely spoken, food is excellent (lots of Indian food!), and Indians can enter visa-free for 30 days.", best_for: ["Developers", "PMs", "Data analysts"] },
  { slug: "ho-chi-minh-city", name: "Ho Chi Minh City", country: "Vietnam", country_code: "VN", continent: "Asia", flag_emoji: "🇻🇳", monthly_total_budget_usd: 900, monthly_rent_usd: 350, monthly_food_usd: 230, monthly_transport_usd: 60, monthly_utilities_usd: 60, internet_speed_mbps: 55, safety_score: 75, english_proficiency: "low", coworking_count: 30, timezone: "Asia/Ho_Chi_Minh", currency_code: "VND", description: "HCMC (Saigon) is one of Southeast Asia's most exciting cities. Insanely cheap food, fast-growing startup scene, and a buzzing energy. Indians require an e-visa.", best_for: ["Developers", "Designers", "Marketers"] },
  { slug: "berlin", name: "Berlin", country: "Germany", country_code: "DE", continent: "Europe", flag_emoji: "🇩🇪", monthly_total_budget_usd: 2800, monthly_rent_usd: 1400, monthly_food_usd: 700, monthly_transport_usd: 200, monthly_utilities_usd: 200, internet_speed_mbps: 88, safety_score: 80, english_proficiency: "high", coworking_count: 100, timezone: "Europe/Berlin", currency_code: "EUR", description: "Berlin is Europe's startup capital. World-class tech scene, incredible arts and culture, and a very international city. Germany has a Freelancer Visa.", best_for: ["Developers", "Founders", "Data engineers"] },
  { slug: "playa-del-carmen", name: "Playa del Carmen", country: "Mexico", country_code: "MX", continent: "Americas", flag_emoji: "🇲🇽", monthly_total_budget_usd: 1200, monthly_rent_usd: 500, monthly_food_usd: 300, monthly_transport_usd: 80, monthly_utilities_usd: 80, internet_speed_mbps: 45, safety_score: 65, english_proficiency: "medium", coworking_count: 20, timezone: "America/Cancun", currency_code: "MXN", description: "Playa del Carmen is the beach alternative to Mexico City. On the Caribbean coast, with warm weather, turquoise water, and a laid-back nomad community.", best_for: ["Developers", "Designers", "Content creators"] },
];

const visaRequirements = [
  { passport_country_code: "IN", destination_country_code: "GE", visa_type: "visa_free", max_stay_days: 365, notes: "Indians can stay in Georgia visa-free for up to 1 year. No registration required for stays under 90 days.", embassy_link: "https://www.geoconsul.gov.ge" },
  { passport_country_code: "IN", destination_country_code: "TH", visa_type: "visa_free", max_stay_days: 30, notes: "Indians get 30 days visa-free. Extendable once for 30 more days at an immigration office for ~1,900 THB.", embassy_link: "https://www.thaiembassy.com" },
  { passport_country_code: "IN", destination_country_code: "MX", visa_type: "visa_free", max_stay_days: 180, notes: "Indians can enter Mexico visa-free for up to 180 days. Fill the FMM tourist card on arrival.", embassy_link: "https://embamex.sre.gob.mx" },
  { passport_country_code: "IN", destination_country_code: "MY", visa_type: "visa_free", max_stay_days: 30, notes: "Indians get 30 days visa-free entry to Malaysia. Extendable at immigration.", embassy_link: "https://www.kln.gov.my" },
  { passport_country_code: "IN", destination_country_code: "ID", visa_type: "visa_on_arrival", max_stay_days: 30, notes: "Visa on Arrival available at major airports. Costs ~$35 USD. Extendable once for 30 more days.", evisa_link: "https://molina.imigrasi.go.id", embassy_link: "https://kemlu.go.id" },
  { passport_country_code: "IN", destination_country_code: "VN", visa_type: "evisa", max_stay_days: 90, notes: "E-visa costs $25 USD, valid for 90 days, single or multiple entry. Apply online 3 days in advance.", evisa_link: "https://evisa.xuatnhapcanh.gov.vn", embassy_link: "https://www.vietnamembassy.org" },
  { passport_country_code: "IN", destination_country_code: "TW", visa_type: "evisa", max_stay_days: 30, notes: "Indians can apply for an e-visa online. Processing takes 3-5 business days.", evisa_link: "https://visawebapp.boca.gov.tw", embassy_link: "https://www.roc-taiwan.org" },
  { passport_country_code: "IN", destination_country_code: "AE", visa_type: "visa_on_arrival", max_stay_days: 14, notes: "Indians with valid US/UK/EU visa can get visa on arrival for 14 days. Otherwise apply for tourist visa online.", evisa_link: "https://icp.gov.ae", embassy_link: "https://www.uaeembassy.in" },
  { passport_country_code: "IN", destination_country_code: "PT", visa_type: "visa_required", max_stay_days: 90, notes: "Schengen visa required. Apply at Portuguese consulate. Processing 15-20 days. Portugal also offers Digital Nomad Visa (D8) for longer stays.", embassy_link: "https://www.vistos.mne.gov.pt" },
  { passport_country_code: "IN", destination_country_code: "DE", visa_type: "visa_required", max_stay_days: 90, notes: "Schengen visa required. Germany also has a Freelancer Visa for longer stays. Apply at German consulate 3-6 weeks in advance.", embassy_link: "https://india.diplo.de" },
  { passport_country_code: "IN", destination_country_code: "EE", visa_type: "visa_required", max_stay_days: 90, notes: "Schengen visa required. Estonia has a Digital Nomad Visa for 1-year stay for remote workers earning over €3,504/month.", embassy_link: "https://www.estonia.eu" },
  { passport_country_code: "IN", destination_country_code: "HU", visa_type: "visa_required", max_stay_days: 90, notes: "Schengen visa required. Apply at Hungarian consulate. Processing takes 15 days.", embassy_link: "https://newdelhi.mfa.gov.hu" },
  { passport_country_code: "IN", destination_country_code: "CZ", visa_type: "visa_required", max_stay_days: 90, notes: "Schengen visa required. Apply at Czech consulate in New Delhi or Mumbai.", embassy_link: "https://www.mzv.cz/newdelhi" },
  { passport_country_code: "IN", destination_country_code: "ES", visa_type: "visa_required", max_stay_days: 90, notes: "Schengen visa required. Spain has a Digital Nomad Visa since 2023 for stays up to 1 year.", embassy_link: "https://www.exteriores.gob.es" },
  { passport_country_code: "IN", destination_country_code: "CO", visa_type: "visa_required", max_stay_days: 90, notes: "Indians require a tourist visa for Colombia. Apply at Colombian embassy in New Delhi.", embassy_link: "https://newdelhi.consulado.gov.co" },
  { passport_country_code: "IN", destination_country_code: "KR", visa_type: "visa_required", max_stay_days: 90, notes: "Indians require K-ETA or visa for South Korea. K-ETA costs $10 and is processed online in 72 hours.", evisa_link: "https://www.k-eta.go.kr", embassy_link: "https://ind.mofa.go.kr" },
  { passport_country_code: "IN", destination_country_code: "ZA", visa_type: "visa_free", max_stay_days: 30, notes: "Indians get 30 days visa-free in South Africa. Yellow fever vaccination certificate required if coming from endemic countries.", embassy_link: "https://www.dirco.gov.za" },
];

const jobs = [
  { title: "Senior React Developer", company: "GitLab", location_type: "remote", india_friendly: true, salary_min_usd: 8000, salary_max_usd: 12000, tech_stack: ["React", "TypeScript", "GraphQL"], job_url: "https://about.gitlab.com/jobs/", source: "direct", is_featured: true },
  { title: "Backend Engineer (Go)", company: "Automattic", location_type: "remote", india_friendly: true, salary_min_usd: 7000, salary_max_usd: 10000, tech_stack: ["Go", "MySQL", "Docker"], job_url: "https://automattic.com/work-with-us/", source: "direct", is_featured: true },
  { title: "Full Stack Developer", company: "Basecamp", location_type: "remote", india_friendly: true, salary_min_usd: 6000, salary_max_usd: 9000, tech_stack: ["Ruby on Rails", "React", "PostgreSQL"], job_url: "https://basecamp.com/about/jobs", source: "direct" },
  { title: "Data Engineer", company: "Hotjar", location_type: "remote", india_friendly: true, salary_min_usd: 5000, salary_max_usd: 8000, tech_stack: ["Python", "Spark", "Airflow", "BigQuery"], job_url: "https://www.hotjar.com/careers/", source: "direct" },
  { title: "Python Developer", company: "Doist", location_type: "remote", india_friendly: true, salary_min_usd: 5500, salary_max_usd: 8000, tech_stack: ["Python", "Django", "PostgreSQL"], job_url: "https://doist.com/jobs/", source: "direct" },
  { title: "Frontend Engineer", company: "Vercel", location_type: "remote", india_friendly: true, salary_min_usd: 7000, salary_max_usd: 11000, tech_stack: ["React", "Next.js", "TypeScript"], job_url: "https://vercel.com/careers", source: "direct", is_featured: true },
  { title: "DevOps Engineer", company: "Supabase", location_type: "remote", india_friendly: true, salary_min_usd: 6000, salary_max_usd: 9000, tech_stack: ["PostgreSQL", "Docker", "Kubernetes"], job_url: "https://supabase.com/careers", source: "direct" },
  { title: "Product Designer", company: "Linear", location_type: "remote", india_friendly: true, salary_min_usd: 5000, salary_max_usd: 8000, tech_stack: ["Figma", "Prototyping", "Design Systems"], job_url: "https://linear.app/careers", source: "direct" },
  { title: "Senior Backend Developer", company: "Lemon Squeezy", location_type: "remote", india_friendly: true, salary_min_usd: 5000, salary_max_usd: 7500, tech_stack: ["Laravel", "PHP", "MySQL"], job_url: "https://www.lemonsqueezy.com/careers", source: "direct" },
  { title: "React Native Developer", company: "Expo", location_type: "remote", india_friendly: true, salary_min_usd: 5000, salary_max_usd: 8000, tech_stack: ["React Native", "TypeScript", "Expo"], job_url: "https://expo.dev/careers", source: "direct" },
  { title: "Machine Learning Engineer", company: "Hugging Face", location_type: "remote", india_friendly: true, salary_min_usd: 8000, salary_max_usd: 14000, tech_stack: ["Python", "PyTorch", "Transformers"], job_url: "https://huggingface.co/jobs", source: "direct", is_featured: true },
  { title: "Site Reliability Engineer", company: "PlanetScale", location_type: "remote", india_friendly: true, salary_min_usd: 7000, salary_max_usd: 10000, tech_stack: ["MySQL", "Go", "Kubernetes"], job_url: "https://planetscale.com/careers", source: "direct" },
  { title: "TypeScript Engineer", company: "Prisma", location_type: "remote", india_friendly: true, salary_min_usd: 6000, salary_max_usd: 9000, tech_stack: ["TypeScript", "Node.js", "PostgreSQL"], job_url: "https://www.prisma.io/careers", source: "direct" },
  { title: "Data Scientist", company: "PostHog", location_type: "remote", india_friendly: true, salary_min_usd: 6000, salary_max_usd: 9000, tech_stack: ["Python", "SQL", "ClickHouse"], job_url: "https://posthog.com/careers", source: "direct" },
  { title: "iOS Developer", company: "Sketch", location_type: "remote", india_friendly: true, salary_min_usd: 5500, salary_max_usd: 8000, tech_stack: ["Swift", "SwiftUI", "Xcode"], job_url: "https://www.sketch.com/careers/", source: "direct" },
  { title: "Senior Node.js Developer", company: "Strapi", location_type: "remote", india_friendly: true, salary_min_usd: 5000, salary_max_usd: 7500, tech_stack: ["Node.js", "TypeScript", "PostgreSQL"], job_url: "https://strapi.io/careers", source: "direct" },
  { title: "Android Developer", company: "Bitwarden", location_type: "remote", india_friendly: true, salary_min_usd: 4500, salary_max_usd: 7000, tech_stack: ["Kotlin", "Android", "Jetpack Compose"], job_url: "https://bitwarden.com/careers/", source: "direct" },
  { title: "Cloud Infrastructure Engineer", company: "Fly.io", location_type: "remote", india_friendly: true, salary_min_usd: 7000, salary_max_usd: 11000, tech_stack: ["Go", "Rust", "Linux", "Networking"], job_url: "https://fly.io/jobs/", source: "direct" },
  { title: "Frontend Developer", company: "Cal.com", location_type: "remote", india_friendly: true, salary_min_usd: 4000, salary_max_usd: 6500, tech_stack: ["React", "Next.js", "Tailwind CSS"], job_url: "https://cal.com/careers", source: "direct" },
  { title: "Rust Engineer", company: "Cloudflare", location_type: "remote", india_friendly: true, salary_min_usd: 9000, salary_max_usd: 14000, tech_stack: ["Rust", "WebAssembly", "Networking"], job_url: "https://www.cloudflare.com/careers/", source: "direct", is_featured: true },
  { title: "Backend Python Engineer", company: "Sentry", location_type: "remote", india_friendly: true, salary_min_usd: 6000, salary_max_usd: 9000, tech_stack: ["Python", "Django", "Kafka", "Redis"], job_url: "https://sentry.io/careers/", source: "direct" },
  { title: "Staff Frontend Engineer", company: "Netlify", location_type: "remote", india_friendly: true, salary_min_usd: 9000, salary_max_usd: 13000, tech_stack: ["React", "TypeScript", "GraphQL"], job_url: "https://www.netlify.com/careers/", source: "direct" },
  { title: "Platform Engineer", company: "Render", location_type: "remote", india_friendly: true, salary_min_usd: 7000, salary_max_usd: 10000, tech_stack: ["Go", "Kubernetes", "PostgreSQL"], job_url: "https://render.com/careers", source: "direct" },
  { title: "UX Engineer", company: "Intercom", location_type: "remote", india_friendly: true, salary_min_usd: 5500, salary_max_usd: 8500, tech_stack: ["React", "Ember.js", "Figma"], job_url: "https://www.intercom.com/careers", source: "direct" },
  { title: "Security Engineer", company: "1Password", location_type: "remote", india_friendly: true, salary_min_usd: 8000, salary_max_usd: 12000, tech_stack: ["Go", "Rust", "Cryptography"], job_url: "https://1password.com/careers/", source: "direct" },
];

async function seed() {
  console.log("Seeding cities...");
  const { error: citiesError } = await supabase.from("cities").upsert(cities, { onConflict: "slug" });
  if (citiesError) { console.error("Cities error:", citiesError); process.exit(1); }
  console.log(`✓ ${cities.length} cities seeded`);

  console.log("Seeding visa requirements...");
  const { error: visaError } = await supabase.from("visa_requirements").upsert(visaRequirements, { onConflict: "passport_country_code,destination_country_code" });
  if (visaError) { console.error("Visa error:", visaError); process.exit(1); }
  console.log(`✓ ${visaRequirements.length} visa entries seeded`);

  console.log("Seeding jobs...");
  const { error: jobsError } = await supabase.from("jobs").upsert(jobs, { onConflict: "job_url" });
  if (jobsError) { console.error("Jobs error:", jobsError); process.exit(1); }
  console.log(`✓ ${jobs.length} jobs seeded`);

  console.log("\n✅ All data seeded successfully!");
}

seed();
